# students Record
name=input("Enter your Name :: ")
roll=input("Enter your Roll no. :: ")
clas=input("Enter your Class :: ")
div=input("Enter your Div :: ")
sub=input("Enter your Subject :: ")
college=input("Enter your College :: ")
sem=input("Enter your Semester :: ")
dob=input("Enter your D.O.B :: ")
address=input("Enter your Home Address :: ")
tele=input("Enter your Telephone No. :: ")
email=input("Enter your Email :: ")

print("\n\nName :: ",name,type(name))
print("Roll no. :: ",roll,type(roll))
print("Class :: ",clas,type(clas))
print("Div :: ",div,type(div))
print("Subject :: ",sub,type(sub))
print("College :: ",college,type(college))
print("Semester :: ",sem,type(sem))
print("D.O.B :: ",dob,type(dob))
print("Home Address :: ",address,type(address))
print("Telephone No. :: ",tele,type(tele))
print("Email :: ",email,type(email))